# Site settings
title: radorables
description:
url: https://www.radorables.com
#baseurl: /radorables.github.io
# User settings
username: radorables
email: info@radorables.com

# Global settings
icon_size: 58

plugins:
  - jekyll-seo-tag
